# Customize site navigation
nav:
- name: 首页
  url: /
- name: 归档
  url: /archives.html
- name: 关于
  url: /about.html

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- icon: false    #github
  link: https://github.com/professordeng/simple
- icon: false    # weibo
  link: https://weibo.com/codeng
- icon: false
  link: https://t.me/jekyll_simple
- icon: false
  link: https://zhihu.com/people/professordeng
- icon: false
  link: https://linkedin.com/in/professordeng
  
# Customize site text
prev: 上一篇
next: 下一篇

prev_page: 上一页
next_page: 下一页

search_tip: 输入关键字
searching: 搜索

new: New

read_more: Read More

edit: edit
